version: '3'
services:
  redis:
    image: "redis"
    container_name: redis-container
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: mongo-gui-container
    restart: always
    ports:
      - "6503:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo
  
  web:
    build: ./backend
    container_name: go-server
    restart: always
    ports:
      - "6500:6500"
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./frontend
    container_name: svelte-frontend
    restart: always
    ports:
      - "6501:6501"
    depends_on:
      - web